name: Behat
on: pull_request

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    name: php${{ matrix.php-versions }}

    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Set up dependencies
        run: composer install

      - name: Run behat
        run: |
          export BEHAT_RUN_AS=$(ls -ld behat.yml | awk '{print $3}')
          export BEHAT_VERBOSE="$RUNNER_DEBUG"
          vendor/bin/behat
