name: Lint
on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    name: Psalm check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: vendor/bin/psalm
